[package]
authors = ["root"]
name = "doory-strikeplate"
version = "0.1.0"

[dependencies]
bincode = "1.0.1"
env_logger = "0.4.3"
hyper = "0.10.5"
log = "0.3.8"
serde = "1.0.79"
serde_derive = "1.0.79"
serde_json = "1.0.31"

[dependencies.doory-core]
path = "../doory-core"
